name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup SirixDB server
      run: docker-compose -f ./tests/resources/docker-compose.yml up -d keycloak
    - name: Build crate
      run: cargo build --all-features --verbose
    - name: Run tests
      run: bash ./prepare-test.sh && cargo test --all-features --verbose